language: node_js
node_js:
  - "4.1"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: npm run coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aeb9d8c8e74a3d439975
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always